run_name: OLMo2-1B-stage1
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: olmo-small
  group: ${run_name}
  entity: 2524258132-zhijiang

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: false
  alibi: false
  rope: true
  rope_theta: 500000
  flash_attention: true
  attention_dropout: 0.0
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm: true
  attention_layer_norm_with_affine: true
  norm_after: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 100278
  embedding_size: 100352
  eos_token_id: 100257
  pad_token_id: 100277
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

softmax_auxiliary_loss: true
auxiliary_loss_multiplier: 1e-5
fused_loss: true

compile: null

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 1

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 10066329
  t_max: 6e9
  alpha_f: 0.1
  warmup_min_lr: 0.0

tokenizer:
  identifier: tokenizers/allenai_dolma2.json
  truncate_direction: right

save_folder: http://olmo-data.org/checkpoints/OLMo-small/${run_name}
save_overwrite: true

save_interval: 1000
save_interval_ephemeral: 1000
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 5e9T
global_train_batch_size: 512
device_train_microbatch_size: 4

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  sharding_strategy: SHARD_GRAD_OP
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

gen1_gc_interval: 10

eval_interval: 1000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # - label: all-small-ppl-validation
  #   data:
  #     num_workers: 0
  #     drop_last: true
  #     # generate_doc_lengths: true
  #     memmap_dtype: uint32
  #     datasets:
  #       c4_en-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/c4_en/val/part-0-00000.npy
  #       dolma_books-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_books/val/part-0-00000.npy
  #       dolma_common-crawl-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_common-crawl/val/part-0-00000.npy
  #       dolma_pes2o-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_pes2o/val/part-0-00000.npy
  #       dolma_reddit-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_reddit/val/part-0-00000.npy
  #       dolma_stack-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_stack/val/part-0-00000.npy
  #       dolma_wiki-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_wiki/val/part-0-00000.npy
  #       ice-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/ice/val/part-0-00000.npy
  #       m2d2_s2orc-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/m2d2_s2orc/val/part-0-00000.npy
  #       pile-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/pile/val/part-0-00000.npy
  #       wikitext_103-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/wikitext_103/val/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  - label: boolq
    type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  - label: arc_challenge
    type: downstream

  - label: copa
    type: downstream

  #- label: rte
  #  type: downstream

  #- label: commitment_bank
  #  type: downstream

  #- label: sst2
  #  type: downstream

  - label: commonsense_qa
    type: downstream

  - label: social_iqa
    type: downstream

  - label: mmlu_stem_var
    type: downstream

  - label: mmlu_humanities_var
    type: downstream

  - label: mmlu_social_sciences_var
    type: downstream

  - label: mmlu_other_var
    type: downstream

  - label: mmlu_stem_mc_5shot
    type: downstream

  - label: mmlu_humanities_mc_5shot
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

  - label: mmlu_other_mc_5shot
    type: downstream

  - label: mmlu_stem_mc_5shot_test
    type: downstream

  - label: mmlu_humanities_mc_5shot_test
    type: downstream

  - label: mmlu_social_sciences_mc_5shot_test
    type: downstream

  - label: mmlu_other_mc_5shot_test
    type: downstream

  - label: basic_arithmetic
    type: downstream

  - label: trivia_qa_wiki_ppl
    type: downstream

  - label: natural_qs_open_ppl
    type: downstream

  - label: arc_easy_ppl
    type: downstream

data:
  pad_direction: right
  # generate_doc_lengths: true
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  memmap_dtype: uint32
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/Arxiv/part-00-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/Pes2o/part-06-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/OpenWebMath/part-02-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/OpenWebMath/part-03-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/starcoder/part-001-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/starcoder/part-002-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/starcoder/part-003-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/starcoder/part-004-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/starcoder/part-005-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/starcoder/part-007-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/Wikipedia/part-0-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/Wikipedia/part-1-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-000-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-000-00001.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-000-00002.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-000-00003.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-000-00004.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-001-00000.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-001-00001.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-001-00002.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-001-00003.npy
    - /mnt/zhongziban8-dclm/zzl/datasets-stage1/DCLM/part-001-00004.npy

